MonsieurBiz\SyliusAdvancedShippingPlugin\Entity\ShippingCalculatorConfigurationTranslation:
    properties:
        name:
            -   NotBlank:
                    groups: [monsieurbiz_advanced_shipping]
            -   Length:
                    min: 2
                    max: 255
                    groups: [monsieurbiz_advanced_shipping]
