MonsieurBiz\SyliusAdvancedShippingPlugin\Entity\ShippingTypeTranslation:
    properties:
        label:
            -   NotBlank:
                    groups: [ monsieurbiz_advanced_shipping ]
            -   Length:
                    min: 2
                    max: 255
                    groups: [ monsieurbiz_advanced_shipping ]
        description:
            -   Length:
                    min: 2
                    max: 255
                    groups: [ monsieurbiz_advanced_shipping ]
