monsieurbiz_advanced_shipping_admin_get_shipping_calculators:
    path: /shipping-calculators
    methods: [GET]
    defaults:
        _controller: MonsieurBiz\SyliusAdvancedShippingPlugin\Controller\ShippingCalculatorController::getListAction
        template: '@MonsieurBizSyliusAdvancedShippingPlugin/Admin/Calculator/list.html.twig'
        _sylius:
            permission: true

monsieurbiz_advanced_shipping_admin_get_shipping_address_providers:
    path: /shipping-adress-providers
    methods: [GET]
    defaults:
        _controller: MonsieurBiz\SyliusAdvancedShippingPlugin\Controller\ShippingAddressProviderController::getProviderListAction
        template: '@MonsieurBizSyliusAdvancedShippingPlugin/Admin/AddressProvider/list.html.twig'
        _sylius:
            permission: true

monsieurbiz_advanced_shipping_admin_get_map_providers:
    path: /map-providers
    methods: [GET]
    defaults:
        _controller: MonsieurBiz\SyliusAdvancedShippingPlugin\Controller\MapProviderController::getProviderListAction
        template: '@MonsieurBizSyliusAdvancedShippingPlugin/Admin/MapProvider/list.html.twig'
        _sylius:
            permission: true
